corrected dan attack
RomiconEZ/llamator pull request #35
Opened 2024-11-09 11:47 UTC by NickoJo

исправил логику `dan` и `ru_dan`
раньше атакующие модели сбивались при обработке длинного шаблона для генерации `dan_prompt`, 
сейчас логика атаки идентична `ucar`, в защищающую модель загоняется исходный промпт, без обработки.

также чуть-чуть поменял логику проверки

2024-11-09 12:20 UTC, lattaai5 commented
Hello, I tried to fix the issue

This is what I did:

Modified the TestDAN class to use a static prompt similar to UCAR attack. Updated the verification logic to check for 'dan' in the response.

I also created pull request: https://github.com/RomiconEZ/llamator/pull/36


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

2024-11-09 13:24 UTC, nizamovtimur requested changes
Было бы здорово, чтобы промтов DAN было несколько, есть как минимум [эта репа](https://github.com/friuns2/BlackFriday-GPTs-Prompts/blob/main/Jailbreaks.md), откуда можно стащить промты + перевести на русский. Поэтому предлагаю заменить хардкод одного промта на паркетник с несколькими атакующими портами (лучше мб один паркетник с дополнительным столбцом для языка) и тогда уже смерджить, зафиналив эту таску

upd. У юкара тоже ведь один промт, может вообще объединить в одну атаку дэн и юкар, которая будет прогонять по одному паркетнику (в котором будут столбцы "тип атаки", "язык" и тп)?

2024-11-09 13:24 UTC, nizamovtimur commented on src/llamator/attacks/dan.py
`dan_prompt_template = dan_prompt = ...`
Лол

2024-11-15 13:24 UTC, nizamovtimur commented
вот еще забавная репа с промт-инъекциями https://github.com/FonduAI/awesome-prompt-injection

2024-11-21 20:24 UTC, NickoJo commented
по юкару и дену вынес промпты в `ucar-dan_prompts.parquet`.
структура:
`dan,ucar,ru_dan,ru_ucar`

пока там по одному промпту, но постепенно буду этот файл пополнять, уже нашел пару репок. но займусь этим позже.
в ходе атаке выдергивается строка из соответствующего столбца.

2024-11-21 20:28 UTC, NickoJo commented
> вот еще забавная репа с промт-инъекциями https://github.com/FonduAI/awesome-prompt-injection

в будущем ваще можно будет дабы не мельтешить отдельными дэнами и юкарами просто в общий py файл собрать аля jailbreaks и выбирать из датасета много таких перемешанных промптов и гонять.
суть у атак и промтов одна.
но это на подумать

2024-11-22 07:46 UTC, nizamovtimur approved these changes

2024-11-22 07:46 UTC, merged