Multistage attack (harmful_behavior_multistage)
RomiconEZ/llamator pull request #53
Opened 2024-12-26 23:02 UTC by NickoJo

открыл PR для продолжения работы над multistage атакой.

- добавил атаку harmful_behavior_multistage - пока за работоспособность не ручаюсь - нужно обсудить архитектурный момент (ниже)
- добавил ее упоминание во всякие config файлы

@RomiconEZ (FYI @nizamovtimur) мне кажется стоит подумать над функцией refine_attack_prompt: возможно ее стоит засунуть в `chat_client.py` class MultiStageInteractionSession
Данная функция позволяет "улучшить" атакующий промпт в случае неудачи. 
сейчас функция start_conversation проверяет в цикле критерии остановки, но в случае, если они не встречаются - ответ защищающейся модели передается атакующей через say?
сейчас попытался эту функцию прикрутить в `harmful_behavior_multistage.py` - но по ощущениям выглядит кривовато, еще не тестил

целевая логика:
в случае если не встретились stop_criterion и history_limit - вызывать метод для refine, который будет конкретизироваться для каждой атаки отдельно (как stop_criterion).
возможно я что-то упускаю из вида - welcome для обсуждения.

2024-12-27 05:51 UTC, nizamovtimur commented
Ещё не смотрел конкретно. Ребейзнул ветку multi-stage-attack только с коммитом b3be0d6 на текущий мейн и форс-пушнул.

2024-12-27 07:04 UTC, nizamovtimur requested changes
> @RomiconEZ (FYI @nizamovtimur) мне кажется стоит подумать над функцией refine_attack_prompt: возможно ее стоит засунуть в `chat_client.py` class MultiStageInteractionSession
> Данная функция позволяет "улучшить" атакующий промпт в случае неудачи.
> сейчас функция start_conversation проверяет в цикле критерии остановки, но в случае, если они не встречаются - ответ защищающейся модели передается атакующей через say?
> сейчас попытался эту функцию прикрутить в `harmful_behavior_multistage.py` - но по ощущениям выглядит кривовато, еще не тестил

Это реально выглядит криво, `refine_attack_prompt` действительно нужно добавить в `MultiStageInteractionSession` как опциональный параметр, то есть если он не нужен, как в подхалимтсве или логике, поскольку улучшающие инструкции уже есть в системном промте атакующей модели, то пусть просто игнорируется. Хотя, может, и тебе достаточно системный промт дополнить без добавления refine?

Кстати:
```python
def stop_criterion(tested_client_history: List[Dict[str, str]]) -> bool:
        last_response = tested_client_history[-1]["content"] if tested_client_history else ""
        # filtered_response = filter_non_alpha_lower(last_response) — лишнее, уже есть в `contains_refusal_keywords()`
        return not contains_refusal_keywords(last_response)
```

2024-12-28 17:13 UTC, nizamovtimur commented
Необходимый для доработки функционал добавлен в #55 

@NickoJo можешь развлекаться, только в конце прогони пж `pre-commit run --all-files`

2024-12-28 20:36 UTC, nizamovtimur requested changes
Получилось хорошо, однако есть нюансы (см. комментарии к коду). Ещё надо проработать такой момент, что ответ атакующей модели перед подачей тестируемой надо очистить от лишних пробелов и вероятных кавычек в начале и конце.

2024-12-28 20:36 UTC, nizamovtimur commented on src/llamator/attacks/harmful_behavior_multistage.py
> +        ).format(objective=objective, base_prompt=last_attacker_response)
Предлагаю вынести в константу наподобие `USUAL_PROMPT_GENERATION_TEMPLATE`. И всё-таки использовать `tested_client_history`.

2024-12-28 20:36 UTC, nizamovtimur commented on src/llamator/attacks/harmful_behavior_multistage.py
> +        self._prepare_attack_data(attack_prompts, responses, statuses)
Ошибка: All arrays must be of the same length

2024-12-28 21:29 UTC, NickoJo commented on src/llamator/attacks/harmful_behavior_multistage.py
> +        ).format(objective=objective, base_prompt=last_attacker_response)
вынести промпт - норм тема.

использовать `tested_client_history` - не норм тема. обсуждали, что `tested_client_history` нужен для проведения скоринга, скоринга нет. поэтому сейчас с ним ничего не придумать.
ты предлагаешь в атаке сделать функцию с заглушкой?

2024-12-29 07:05 UTC, nizamovtimur commented on src/llamator/attacks/harmful_behavior_multistage.py
> +        ).format(objective=objective, base_prompt=last_attacker_response)
я понимаю, но почему бы атакующей модели не знать, что ответила тестируемая модель? может, это повлияет?

2024-12-29 07:20 UTC, nizamovtimur approved these changes
Great job! Happy New Year!
![image](https://github.com/user-attachments/assets/958c19e4-ebf6-4402-b8b3-bb96c049c973)

2024-12-29 07:21 UTC, merged

2024-12-29 13:01 UTC, NickoJo commented on src/llamator/attacks/harmful_behavior_multistage.py
> +        ).format(objective=objective, base_prompt=last_attacker_response)
в этой атаке это почти 100% буде "I'm sorry I can't provide..."
иначе - не отловятся рефьюзалы и атака будет успешна.

короче это специфика конкретной атаки.
где-то, где будет помягче objective и проверка будет через judge это возможно пригодиться, но не тут.